Remove test defs that cause a stack overflow in the type checker
---

kind Fmt/sprintf.kind
/opt/homebrew/lib/node_modules/kind-lang/src/kind.js:6227
    function BitsMap$set$(_bits$2, _val$3, _map$4) {
                         ^

RangeError: Maximum call stack size exceeded
    at BitsMap$set$ (/opt/homebrew/lib/node_modules/kind-lang/src/kind.js:6227:26)